# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Yarn cache
        uses: c-hive/gha-yarn-cache@v2

      - name: Install
        run: yarn install

      # Runs a single command using the runners shell
      - name: Check
        run: yarn build:tsc

      # Runs a set of commands using the runners shell
      - name: Build
        run: yarn build:vite

      - name: Package
        run: yarn zip

      - name: Upload
        uses: softprops/action-gh-release@v0.1.14
        with:
          files: |
            build.zip
